version: "3"
services:
  redis:
    networks:
      - redis-net
    image: redis
    container_name: cache-server
    expose:
      - 6379
  app:
    networks:
      - redis-net
    build: ./
    volumes:
      - ./:/usr/src/app
    links:
      - redis
    ports:
      - 8080:8080
    environment:
      - REDIS_URL=redis://cache
      - NODE_ENV=development
      - PORT=8080
    command:
      sh -c 'npm i && node server.js'
networks:
  redis-net:
    driver: bridge